source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.7'

# Image processing
gem 'image_processing', '~> 1.12'
gem 'mini_magick'

# Use mysql as the database for Active Record
gem 'dotenv-rails'
gem 'mysql2', '~> 0.5'

# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# CORS 設定
gem 'rack-cors'

# devise-jwt Doc: https://rubygems.org/gems/devise-jwt
gem 'devise-jwt', '~> 0.11.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # RSpecRails を追加
  gem 'rspec-rails', '~> 5.0'
  # FactoryBot 導入
  gem 'factory_bot_rails'
  # Faker gem 導入
  gem 'faker'
  # pry 導入
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # Rubocop,RSpec gem
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# devise 導入
gem 'devise'
gem 'devise_token_auth'

# Capybara 導入
gem 'capybara', '~> 3.35'
