services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DEV_NAME}
      MYSQL_USER: ${DATABASE_DEV_USER}
      MYSQL_PASSWORD: ${DATABASE_DEV_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./rails-app/artstyle-navigator-back
    # command: bundle exec rails s -b 0.0.0.0
    env_file:
      - ./rails-app/artstyle-navigator-back/.env
    ports:
      - "3000:3000"
    volumes:
      - ./rails-app/artstyle-navigator-back:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s

  frontend:
    build: ./nuxt-app/artstyle-navigator-front
    command: yarn dev
    environment:
      API_URL: http://localhost:3000
    ports:
      - "8000:3000"
    volumes:
      - ./nuxt-app/artstyle-navigator-front:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
